namespace Bars.Stkomleks.Frontend.Generated
{
    using BarsUp;
    using BarsUp.Utils;

	/// <summary>
    /// Манифест ресурсов модуля
    /// </summary>
    internal partial class ResourceManifest
    {
		/// <summary>
        /// Базовая инициализация. 
        ///             Обычно вызывается из T4-шаблонов.
        /// </summary>
        /// <param name="container"/>
        protected override void BaseInit(IResourceManifestContainer container)
        {		
            
            RegisterResource(container, "content/css/form-styles-130c4db5-a9b3-4c6f-b37e-01182825968c.css"); 
            RegisterResource(container, "content/css/form-styles-153ded49-b5ae-4c43-bdb2-a835368c2cf2.css"); 
            RegisterResource(container, "content/css/form-styles-20f3ec7c-e4f4-41e3-b814-2d79b589ae80.css"); 
            RegisterResource(container, "content/css/form-styles-23beb68e-9c91-43c1-a435-257bf4e15d1b.css"); 
            RegisterResource(container, "content/css/form-styles-2efed10a-d54e-46b9-ac19-6b9792c2fb9e.css"); 
            RegisterResource(container, "content/css/form-styles-395dbab2-e4ab-4846-b876-dbf8b577d6d9.css"); 
            RegisterResource(container, "content/css/form-styles-4e04503b-095f-40ac-a590-d3b44110768f.css"); 
            RegisterResource(container, "content/css/form-styles-51b898b7-bab8-4c73-b0d3-856ce114d842.css"); 
            RegisterResource(container, "content/css/form-styles-5384176d-011e-4051-a1ad-61487308dd00.css"); 
            RegisterResource(container, "content/css/form-styles-59e2e72a-5563-4787-bd22-7bdb89882368.css"); 
            RegisterResource(container, "content/css/form-styles-6185abdb-13fa-4e36-a62b-20d4a979c7ec.css"); 
            RegisterResource(container, "content/css/form-styles-67d498ae-2835-45e6-972f-62b96a4979aa.css"); 
            RegisterResource(container, "content/css/form-styles-77a6afbc-c73b-4ee9-af30-3fa36d6a8a37.css"); 
            RegisterResource(container, "content/css/form-styles-7bfd891d-f74e-48c4-9141-e68896e91cc3.css"); 
            RegisterResource(container, "content/css/form-styles-88f43eeb-7601-4451-bc70-14cfe8179b08.css"); 
            RegisterResource(container, "content/css/form-styles-b26c9636-0eb1-412a-be11-c01993a415e2.css"); 
            RegisterResource(container, "content/css/form-styles-b3d0c6e3-6410-4c8b-b359-da6efc0248e9.css"); 
            RegisterResource(container, "content/css/form-styles-d0c2a2f2-1963-47b7-8908-491cb7e146fb.css"); 
            RegisterResource(container, "content/css/form-styles-ebd25f86-9526-4b73-bb5b-329f5758440d.css"); 
            RegisterResource(container, "content/css/form-styles-ecb21833-eea4-4cc6-abf7-af8875eff7fe.css"); 
            RegisterResource(container, "libs/B4/autostart/BarsStkomleks.js"); 
            RegisterResource(container, "libs/B4/controller/CompositionObjectSpecialistsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/CompositionObjectSpecialistsList.js"); 
            RegisterResource(container, "libs/B4/controller/CompositionWorksObjectsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/CompositionWorksObjectsList.js"); 
            RegisterResource(container, "libs/B4/controller/ContactsTypeList.js"); 
            RegisterResource(container, "libs/B4/controller/CurrentPositionsDepartmentsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/CurrentPositionsDepartmentsList.js"); 
            RegisterResource(container, "libs/B4/controller/DepartmentsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/DepartmentsList.js"); 
            RegisterResource(container, "libs/B4/controller/DepartmentsPositionsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/DepartmentsPositionsList.js"); 
            RegisterResource(container, "libs/B4/controller/DepartmentsTypeList.js"); 
            RegisterResource(container, "libs/B4/controller/DocumentsTypeList.js"); 
            RegisterResource(container, "libs/B4/controller/FundingProgramsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/FundingProgramsList.js"); 
            RegisterResource(container, "libs/B4/controller/IndividualsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/IndividualsList.js"); 
            RegisterResource(container, "libs/B4/controller/Map.js"); 
            RegisterResource(container, "libs/B4/controller/ObjectProductsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/ObjectProductsList.js"); 
            RegisterResource(container, "libs/B4/controller/ObjectsDocumentsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/ObjectsDocumentsList.js"); 
            RegisterResource(container, "libs/B4/controller/ObjectsOrdersEditor.js"); 
            RegisterResource(container, "libs/B4/controller/ObjectsOrdersList.js"); 
            RegisterResource(container, "libs/B4/controller/ObjectsOrdersList2.js"); 
            RegisterResource(container, "libs/B4/controller/ObjectsOrdersListMultiAddByZakazEditor.js"); 
            RegisterResource(container, "libs/B4/controller/ObjectsTypesEditor.js"); 
            RegisterResource(container, "libs/B4/controller/ObjectsTypesList.js"); 
            RegisterResource(container, "libs/B4/controller/OrderOrganizationEditor.js"); 
            RegisterResource(container, "libs/B4/controller/OrderOrganizationList.js"); 
            RegisterResource(container, "libs/B4/controller/OrdersEditor.js"); 
            RegisterResource(container, "libs/B4/controller/OrdersList.js"); 
            RegisterResource(container, "libs/B4/controller/OrdersObjectsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/OrdersObjectsEditor_Copy_0.js"); 
            RegisterResource(container, "libs/B4/controller/OrdersObjectsList.js"); 
            RegisterResource(container, "libs/B4/controller/OrdersObjectsList2.js"); 
            RegisterResource(container, "libs/B4/controller/OrganizationContactsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/OrganizationContactsList.js"); 
            RegisterResource(container, "libs/B4/controller/OrganizationEditor.js"); 
            RegisterResource(container, "libs/B4/controller/OrganizationFundingProgramsList.js"); 
            RegisterResource(container, "libs/B4/controller/OrganizationFundingProgramsList2.js"); 
            RegisterResource(container, "libs/B4/controller/OrganizationFundingProgramsListMultiAddByOrganizationEditor.js"); 
            RegisterResource(container, "libs/B4/controller/OrganizationList.js"); 
            RegisterResource(container, "libs/B4/controller/OrganizationProfilesList.js"); 
            RegisterResource(container, "libs/B4/controller/OrganizationProfilesList2.js"); 
            RegisterResource(container, "libs/B4/controller/OrganizationProfilesListMultiAddByOrganizationEditor.js"); 
            RegisterResource(container, "libs/B4/controller/PositionsTypesList.js"); 
            RegisterResource(container, "libs/B4/controller/ProductsEditor.js"); 
            RegisterResource(container, "libs/B4/controller/ProductsList.js"); 
            RegisterResource(container, "libs/B4/controller/ProductsTypesList.js"); 
            RegisterResource(container, "libs/B4/controller/ProfilesOrganizationsList.js"); 
            RegisterResource(container, "libs/B4/controller/RelatedOrganizationsList.js"); 
            RegisterResource(container, "libs/B4/controller/RelatedOrganizationsListMultiAddByOrganizationEditor.js"); 
            RegisterResource(container, "libs/B4/controller/ResponsiblePersonsOrderEditor.js"); 
            RegisterResource(container, "libs/B4/controller/ResponsiblePersonsOrderList.js"); 
            RegisterResource(container, "libs/B4/controller/StaffEditor.js"); 
            RegisterResource(container, "libs/B4/controller/StaffList.js"); 
            RegisterResource(container, "libs/B4/controller/TypesWorkTypesObjectsList.js"); 
            RegisterResource(container, "libs/B4/controller/TypesWorkTypesObjectsListMultiAddByObjectTypeEditor.js"); 
            RegisterResource(container, "libs/B4/controller/UnitMeasureList.js"); 
            RegisterResource(container, "libs/B4/controller/WorksRolesList.js"); 
            RegisterResource(container, "libs/B4/controller/WorksTypesList.js"); 
            RegisterResource(container, "libs/B4/customVTypes/BarsStkomleks.js"); 
            RegisterResource(container, "libs/B4/view/CompositionObjectSpecialistsEditor.js"); 
            RegisterResource(container, "libs/B4/view/CompositionObjectSpecialistsList.js"); 
            RegisterResource(container, "libs/B4/view/CompositionWorksObjectsEditor.js"); 
            RegisterResource(container, "libs/B4/view/CompositionWorksObjectsList.js"); 
            RegisterResource(container, "libs/B4/view/ContactsTypeList.js"); 
            RegisterResource(container, "libs/B4/view/CurrentPositionsDepartmentsEditor.js"); 
            RegisterResource(container, "libs/B4/view/CurrentPositionsDepartmentsList.js"); 
            RegisterResource(container, "libs/B4/view/DepartmentsEditor.js"); 
            RegisterResource(container, "libs/B4/view/DepartmentsList.js"); 
            RegisterResource(container, "libs/B4/view/DepartmentsPositionsEditor.js"); 
            RegisterResource(container, "libs/B4/view/DepartmentsPositionsList.js"); 
            RegisterResource(container, "libs/B4/view/DepartmentsTypeList.js"); 
            RegisterResource(container, "libs/B4/view/DocumentsTypeList.js"); 
            RegisterResource(container, "libs/B4/view/FundingProgramsEditor.js"); 
            RegisterResource(container, "libs/B4/view/FundingProgramsList.js"); 
            RegisterResource(container, "libs/B4/view/IndividualsEditor.js"); 
            RegisterResource(container, "libs/B4/view/IndividualsList.js"); 
            RegisterResource(container, "libs/B4/view/Map.js"); 
            RegisterResource(container, "libs/B4/view/ObjectProductsEditor.js"); 
            RegisterResource(container, "libs/B4/view/ObjectProductsList.js"); 
            RegisterResource(container, "libs/B4/view/ObjectsDocumentsEditor.js"); 
            RegisterResource(container, "libs/B4/view/ObjectsDocumentsList.js"); 
            RegisterResource(container, "libs/B4/view/ObjectsOrdersEditor.js"); 
            RegisterResource(container, "libs/B4/view/ObjectsOrdersList.js"); 
            RegisterResource(container, "libs/B4/view/ObjectsOrdersList2.js"); 
            RegisterResource(container, "libs/B4/view/ObjectsOrdersListMultiAddByZakazEditor.js"); 
            RegisterResource(container, "libs/B4/view/ObjectsTypesEditor.js"); 
            RegisterResource(container, "libs/B4/view/ObjectsTypesList.js"); 
            RegisterResource(container, "libs/B4/view/OrderOrganizationEditor.js"); 
            RegisterResource(container, "libs/B4/view/OrderOrganizationList.js"); 
            RegisterResource(container, "libs/B4/view/OrdersEditor.js"); 
            RegisterResource(container, "libs/B4/view/OrdersList.js"); 
            RegisterResource(container, "libs/B4/view/OrdersObjectsEditor.js"); 
            RegisterResource(container, "libs/B4/view/OrdersObjectsEditor_Copy_0.js"); 
            RegisterResource(container, "libs/B4/view/OrdersObjectsList.js"); 
            RegisterResource(container, "libs/B4/view/OrdersObjectsList2.js"); 
            RegisterResource(container, "libs/B4/view/OrganizationContactsEditor.js"); 
            RegisterResource(container, "libs/B4/view/OrganizationContactsList.js"); 
            RegisterResource(container, "libs/B4/view/OrganizationEditor.js"); 
            RegisterResource(container, "libs/B4/view/OrganizationFundingProgramsList.js"); 
            RegisterResource(container, "libs/B4/view/OrganizationFundingProgramsList2.js"); 
            RegisterResource(container, "libs/B4/view/OrganizationFundingProgramsListMultiAddByOrganizationEditor.js"); 
            RegisterResource(container, "libs/B4/view/OrganizationList.js"); 
            RegisterResource(container, "libs/B4/view/OrganizationProfilesList.js"); 
            RegisterResource(container, "libs/B4/view/OrganizationProfilesList2.js"); 
            RegisterResource(container, "libs/B4/view/OrganizationProfilesListMultiAddByOrganizationEditor.js"); 
            RegisterResource(container, "libs/B4/view/PositionsTypesList.js"); 
            RegisterResource(container, "libs/B4/view/ProductsEditor.js"); 
            RegisterResource(container, "libs/B4/view/ProductsList.js"); 
            RegisterResource(container, "libs/B4/view/ProductsTypesList.js"); 
            RegisterResource(container, "libs/B4/view/ProfilesOrganizationsList.js"); 
            RegisterResource(container, "libs/B4/view/RelatedOrganizationsList.js"); 
            RegisterResource(container, "libs/B4/view/RelatedOrganizationsListMultiAddByOrganizationEditor.js"); 
            RegisterResource(container, "libs/B4/view/ResponsiblePersonsOrderEditor.js"); 
            RegisterResource(container, "libs/B4/view/ResponsiblePersonsOrderList.js"); 
            RegisterResource(container, "libs/B4/view/StaffEditor.js"); 
            RegisterResource(container, "libs/B4/view/StaffList.js"); 
            RegisterResource(container, "libs/B4/view/TypesWorkTypesObjectsList.js"); 
            RegisterResource(container, "libs/B4/view/TypesWorkTypesObjectsListMultiAddByObjectTypeEditor.js"); 
            RegisterResource(container, "libs/B4/view/UnitMeasureList.js"); 
            RegisterResource(container, "libs/B4/view/WorksRolesList.js"); 
            RegisterResource(container, "libs/B4/view/WorksTypesList.js"); 
        }        
    }
}
